version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/app
      - /app/node_modules 
    environment:
      DATABASE_CLIENT: sqlite
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped